### PR TITLE
Make incremental bullets work in presenter again

### LINKED ISSUE #132: Slides with bullets incremental can´t be shown via /presenter
I create a presentation named Foo

```
showoff create Foo
```

cd into the directory and start showoff

```
cd Foo
showoff serve
```

I didn`t touch anything in the default slide.

```
!SLIDE 
# My Presentation #

!SLIDE bullets incremental
# Bullet Points #

* first point
* second point
* third point
```

Now i open a presenter on localhost:9090/presenter.
It opens with the Slide "My Presentation". After pressing SPACE and advancing to the next slide "Bullet points" pressing SPACE doesn´t work anymore. I can´t show the bulletpoints.

Even if i insert a slide after the "Bulltetpoint" slide, it does not advance.
I tried this on Mac OSX 10.9.2 with Firefox, Safari and Chrome. 

Opening localhost:9090 (without presenter) shows everything as expected and incremental bulletpoints do work. 

Opening localhost:9090 (as follower of a presenter) does not work in this context, because the presenter stucks.

Opening the presenter and a slave window also is woking odd. I can navigate the slave window, it does change the presenter and followers, but if the slave window shows bullets incremental, these are neither shown in the presenter nor in the following windows. After all bullets are shown and the slave advances to a new slide, this slide is shown in the presenter and the followers.

Is there anything I can do, to get the presenter working correct ?

### PR DESCRIPTION
**Pull request by binford2k**
- remote tracking was killing the incremental bullets. It would enable
  the next bullet, then immediately reload the slide :(
- Disables incremental bullets on the next view. Just show all bullets.
- In the presenter, don't hide invisible bullets, just dim them out.

Fixes #132

### CODE REVIEW

File: public/js/showoff.js [hunk 1]
```diff
@@ -297,8 +297,9 @@ function setupSlideParamsCheck() {
 }
 
 function gotoSlide(slideNum, updatepv) {
-  slidenum = parseInt(slideNum);
-  if (!isNaN(slidenum)) {
+  newslide = parseInt(slideNum);
```
Comment (marrero984) [inline public/js/showoff.js]: Missing var declaration

File: public/js/showoff.js [hunk 2]
```diff
@@ -444,9 +449,9 @@ function showIncremental(incr)
 {
 		elem = incrElem.eq(incrCurr)
 		if (incrCode && elem.hasClass('command')) {
-			incrElem.eq(incrCurr).css('visibility', 'visible').jTypeWriter({duration:1.0})
+			incrElem.eq(incrCurr).removeClass('hidden').jTypeWriter({duration:1.0})
```
Comment (marrero984) [inline public/js/showoff.js]: Missing ;

File: public/js/showoff.js [hunk 3]
```diff
@@ -444,9 +449,9 @@ function showIncremental(incr)
...
 		} else {
-			incrElem.eq(incrCurr).css('visibility', 'visible')
+			incrElem.eq(incrCurr).removeClass('hidden')
```
Comment (marrero984) [inline public/js/showoff.js]: Missing ;

File: public/js/showoff.js [hunk 4]
```diff
@@ -436,7 +441,7 @@ function determineIncremental()
 		incrCode = true
 	}
 	incrElem.each(function(s, elem) {
-		$(elem).css('visibility', 'hidden');
+		$(elem).addClass('incremental hidden');
```
Comment (marrero984) [inline public/js/showoff.js:444]: Not sure if this will be an issue: 
  Adding 'incremental hidden' here, but only removing 'hidden' in showIncremental.  Could this potentially lead to incremental being added multiple times to the same element?

Comment (binford2k) [inline public/js/showoff.js:444]: No, testing shows it to not be a problem.
